import { chromium } from "playwright-core";
const browser = await chromium.connectOverCDP("http://[::1]:9222");
const context = browser.contexts()[0] ?? (await browser.newContext());
const page = await context.newPage();
const errs = [];
page.on("pageerror", (e) => errs.push((e.stack ?? e.message).split("\n").slice(0, 8).join("\n")));
await page.goto("http://192.168.1.2:8090/docker", { waitUntil: "domcontentloaded" });
await page.waitForTimeout(6000);
console.log(errs.length ? errs.join("\n---\n") : "geen pageerror");
await page.close();
process.exit(0);
