import { chromium } from "playwright-core";
const browser = await chromium.connectOverCDP("http://[::1]:9222");
const context = browser.contexts()[0] ?? (await browser.newContext());
const page = await context.newPage();
await page.setViewportSize({ width: 1440, height: 900 });
await page.goto("http://192.168.1.2:8090/docker", { waitUntil: "domcontentloaded" });
await page.waitForTimeout(5000);
const body = await page.textContent("body");
console.log("panel aanwezig:", body.includes("Container updates"));
console.log("updates badge:", (body.match(/\d+ updates? available/) ?? ["geen"])[0]);
console.log("spotweb rij:", body.includes("spotweb"));
const updButtons = await page.getByRole("button", { name: /^Update$/ }).count();
console.log("'Update' knoppen (zonder aria-label):", updButtons);
const allBtns = await page.locator("button", { hasText: "Update" }).count();
console.log("knoppen met tekst 'Update':", allBtns);
await page.close();
process.exit(0);
